version: '3.7'

services:

  openldap:
    container_name: openldap
    build:
      context: ./openldap
      dockerfile: Dockerfile
    env_file: ./openldap/openldap.env
    ports:
      - "389:389"
      - "636:636"

  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
      - "8443:8443"
    volumes:
      - .:/export
    env_file: ./keycloak/keycloak.env
    depends_on:
      - openldap

  flowable:
    container_name: flowable
    image: flowable/all-in-one
    #build:
    #  context: ./k
    #  dockerfile: Dockerfile
    ports:
      - "8080:8080"
    #  - "8443:8443"
    #volumes:
    #  - .:/export
    env_file: ./flowable.env
    depends_on:
      - keycloak

